[package]
name = "wallet-adapter-common"
version.workspace = true
edition.workspace = true

[dependencies]
# crates.io
anyhow.workspace = true
async-trait.workspace = true
serde = { workspace = true, features = ["derive"] }
solana-sdk.workspace = true
